// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.petstatistic.domain;

import com.petstatistic.domain.HistoryLog;
import com.petstatistic.domain.HistoryLogDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect HistoryLogDataOnDemand_Roo_DataOnDemand {
    
    declare @type: HistoryLogDataOnDemand: @Component;
    
    private Random HistoryLogDataOnDemand.rnd = new SecureRandom();
    
    private List<HistoryLog> HistoryLogDataOnDemand.data;
    
    public HistoryLog HistoryLogDataOnDemand.getNewTransientHistoryLog(int index) {
        HistoryLog obj = new HistoryLog();
        setConnectTimes(obj, index);
        setHistoryDate(obj, index);
        setUserId(obj, index);
        return obj;
    }
    
    public void HistoryLogDataOnDemand.setConnectTimes(HistoryLog obj, int index) {
        Long connectTimes = new Integer(index).longValue();
        obj.setConnectTimes(connectTimes);
    }
    
    public void HistoryLogDataOnDemand.setHistoryDate(HistoryLog obj, int index) {
        Date historyDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setHistoryDate(historyDate);
    }
    
    public void HistoryLogDataOnDemand.setUserId(HistoryLog obj, int index) {
        Long userId = new Integer(index).longValue();
        obj.setUserId(userId);
    }
    
    public HistoryLog HistoryLogDataOnDemand.getSpecificHistoryLog(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        HistoryLog obj = data.get(index);
        Long id = obj.getId();
        return HistoryLog.findHistoryLog(id);
    }
    
    public HistoryLog HistoryLogDataOnDemand.getRandomHistoryLog() {
        init();
        HistoryLog obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return HistoryLog.findHistoryLog(id);
    }
    
    public boolean HistoryLogDataOnDemand.modifyHistoryLog(HistoryLog obj) {
        return false;
    }
    
    public void HistoryLogDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = HistoryLog.findHistoryLogEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'HistoryLog' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<HistoryLog>();
        for (int i = 0; i < 10; i++) {
            HistoryLog obj = getNewTransientHistoryLog(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
