// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.petstatistic.domain;

import com.petstatistic.domain.UsageState;
import com.petstatistic.domain.UsageStateDataOnDemand;
import com.petstatistic.domain.UsageStateIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UsageStateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UsageStateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UsageStateIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UsageStateIntegrationTest: @Transactional;
    
    @Autowired
    private UsageStateDataOnDemand UsageStateIntegrationTest.dod;
    
    @Test
    public void UsageStateIntegrationTest.testCountUsageStates() {
        Assert.assertNotNull("Data on demand for 'UsageState' failed to initialize correctly", dod.getRandomUsageState());
        long count = UsageState.countUsageStates();
        Assert.assertTrue("Counter for 'UsageState' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UsageStateIntegrationTest.testFindUsageState() {
        UsageState obj = dod.getRandomUsageState();
        Assert.assertNotNull("Data on demand for 'UsageState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsageState' failed to provide an identifier", id);
        obj = UsageState.findUsageState(id);
        Assert.assertNotNull("Find method for 'UsageState' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UsageState' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UsageStateIntegrationTest.testFindAllUsageStates() {
        Assert.assertNotNull("Data on demand for 'UsageState' failed to initialize correctly", dod.getRandomUsageState());
        long count = UsageState.countUsageStates();
        Assert.assertTrue("Too expensive to perform a find all test for 'UsageState', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UsageState> result = UsageState.findAllUsageStates();
        Assert.assertNotNull("Find all method for 'UsageState' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UsageState' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UsageStateIntegrationTest.testFindUsageStateEntries() {
        Assert.assertNotNull("Data on demand for 'UsageState' failed to initialize correctly", dod.getRandomUsageState());
        long count = UsageState.countUsageStates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UsageState> result = UsageState.findUsageStateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UsageState' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UsageState' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UsageStateIntegrationTest.testFlush() {
        UsageState obj = dod.getRandomUsageState();
        Assert.assertNotNull("Data on demand for 'UsageState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsageState' failed to provide an identifier", id);
        obj = UsageState.findUsageState(id);
        Assert.assertNotNull("Find method for 'UsageState' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUsageState(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UsageState' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsageStateIntegrationTest.testMergeUpdate() {
        UsageState obj = dod.getRandomUsageState();
        Assert.assertNotNull("Data on demand for 'UsageState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsageState' failed to provide an identifier", id);
        obj = UsageState.findUsageState(id);
        boolean modified =  dod.modifyUsageState(obj);
        Integer currentVersion = obj.getVersion();
        UsageState merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'UsageState' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UsageStateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UsageState' failed to initialize correctly", dod.getRandomUsageState());
        UsageState obj = dod.getNewTransientUsageState(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UsageState' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UsageState' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UsageState' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UsageStateIntegrationTest.testRemove() {
        UsageState obj = dod.getRandomUsageState();
        Assert.assertNotNull("Data on demand for 'UsageState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'UsageState' failed to provide an identifier", id);
        obj = UsageState.findUsageState(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UsageState' with identifier '" + id + "'", UsageState.findUsageState(id));
    }
    
}
