// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.petstatistic.domain;

import com.petstatistic.domain.UsageState;
import com.petstatistic.domain.UsageStateDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UsageStateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UsageStateDataOnDemand: @Component;
    
    private Random UsageStateDataOnDemand.rnd = new SecureRandom();
    
    private List<UsageState> UsageStateDataOnDemand.data;
    
    public UsageState UsageStateDataOnDemand.getNewTransientUsageState(int index) {
        UsageState obj = new UsageState();
        setUserId(obj, index);
        return obj;
    }
    
    public void UsageStateDataOnDemand.setUserId(UsageState obj, int index) {
        String userId = "userId_" + index;
        obj.setUserId(userId);
    }
    
    public UsageState UsageStateDataOnDemand.getSpecificUsageState(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UsageState obj = data.get(index);
        Long id = obj.getId();
        return UsageState.findUsageState(id);
    }
    
    public UsageState UsageStateDataOnDemand.getRandomUsageState() {
        init();
        UsageState obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return UsageState.findUsageState(id);
    }
    
    public boolean UsageStateDataOnDemand.modifyUsageState(UsageState obj) {
        return false;
    }
    
    public void UsageStateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UsageState.findUsageStateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UsageState' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UsageState>();
        for (int i = 0; i < 10; i++) {
            UsageState obj = getNewTransientUsageState(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
