// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.petstatistic.domain;

import com.petstatistic.domain.UsageState;

privileged aspect UsageState_Roo_JavaBean {
    
    public String UsageState.getUserId() {
        return this.userId;
    }
    
    public void UsageState.setUserId(String userId) {
        this.userId = userId;
    }
    
}
